const palette = {
  primary: '#2c4dae',
  white: '#ffffff',
  black: '#000000',
  aliceBlue: '#F5F8FF',
  lavenderMist: '#DCE3F8',
  angry: '#F36C7C',
  lightYellow: '#FFF4CC',
  lightBlue: '#3C58B5',
  lavender: '#e7ebf6',
  ghostWhite: '#fbfcff',
  lightBlack: 'rgba(0,0,0,0.6)',
  carteBlanche: '#EEF2FF',
  shadeOfBlack: 'rgba(0,0,0,0.8)',
  ultraMass: '#f3d467',
  nobilityBlue: '#a2abc4',
  lightGreen: '#70b39d',
  blueChalk: '#eaf3ff',
  shadeOfBlue: '#e7edff',
  mediumShadeOfBlue: '#949db6',
  lightShadeOfBlue: '#d0d7e8',
  lightGrey: '#3a3a3a',
  ghostWhites: '#f4f5ff',
};

export default palette;
