const RouteConfig = {
  SplashNavigator: 'SplashNavigator',
  LoginNavigator: 'LoginNavigator',
  Otp: 'Otp',
  Help: 'Help',
  ProjectDetails: 'ProjectDetails',
  Projects: 'Projects',
  MyTeam: 'MyTeam',
  Attendance: 'Attendance',
  MyDay: 'MyDay',
  LeaveRequests: 'LeaveRequests',
  ApplyLeave: 'ApplyLeave',
  Approve: 'Approve',
  CrewCalendar: 'CrewCalendar',
  ClinetInfo: 'ClinetInfo',
  SendUpdates: 'SendUpdates',
  CapturePics: 'CapturePics',
  Notifications: 'Notifications',
  CrewDetails: 'CrewDetails',
  CrewProfile: 'CrewProfile',
  Insights: 'Insights',
  Trainings: 'Trainings',
  Benefits: 'Benefits',
  ProfileProjects: 'ProfileProjects',
  ProfileProjectDetails: 'ProfileProjectDetails',
  HelpAndSupport: 'HelpAndSupport',
  EnterOTP: 'EnterOTP',
  Login: "Login"
};

export default RouteConfig;
