export default {
  validateUser: '/api/user/validate',
  sendOTP: '/api/send-otp',
  validateMobile: '/node/painter/validate-mobile/',
  verifyOtp: '/node/painter/validate-otp/',
  myDayInfo: '/node/user/myday-info/',
  getCrewCalendar: '/node/painter-crew-calendar/',
  requestForQualityCheck: '/api/user/requestForQualityCheck',
  updateLeftMaterial: '/sfdc/update-leftover-materials-BOM/',
  assignCrewToProject: '/sfdc/assign-crew-to-project/',
  qualityCheckRequest: '/sfdc/update-project-qc-request/',
  scheduleSiteVisit: '/sfdc/create-event/',
  myProjectDetails: '/sfdc/expose-project-details/',
  //upsertUserLeaves: '/sfdc/upsert-user-leaves/',
  upsertUserLeaves: '/sfdc/upsert-leaves-or-attendance/',
  leaveApproveForTL: '/sfdc/leave-approvals-TL/',
  getUserProfile: '/sfdc/expose-user/',
  getNotifications: '/sfdc/expose-user-notifications/',
  updateNotification: '/sfdc/update-notification/',
  markAttendance: '/node/painter-mark-attendance/',
  applyLeave: '/node/painter-apply-leave/',
  teamLeadtraining: '/sfdc/training-by-trainee-users/',
  crewTraining: '/sfdc/expose-training-by-crew-members/',
  leavesHistory: '/node/painter-get-leaves-history/',
  leavesApproval: '/node/painter-get-leaves-approval/',
  upsertLeaves: '/sfdc/upsert-leaves-or-attendance/',
  getSiteCheckList:
    '/bin/api/getFragmentNoKeys?path=/content/dam/grasim-com/app-core/painter-details/painter-site-checklist',
  accessToken: '/sfdc/access-token/',
  updateDatesWithoutRoomSequence:
    '/sfdc/update-room-project-dates-without-room-sequence/',
  updateSiteChecklist: 'sfdc/update-site-checklist/',
};
